### ISSUE TITLE
Test Internet Speed not working

### ISSUE THREAD

**Issue by flyingsonu122** [ayushi7rawat/Youtube-Projects#4]
[Test Internet Speed](https://github.com/ayushi7rawat/Youtube-Projects/tree/master/Test%20Internet%20Speed) is not working,

```$
 module 'speedtest' has no attribute 'Speedtest'
```

**Comment by arunvemana** [comment]
@flyingsonu122  u have to do `pip install speedtest-cli` not `pip install speedtest` , then this issue will be fixed.
